### ISSUE TITLE
AttributeError: 'SpikeSelector' object has no attribute 'select_spikes'

### ISSUE THREAD

**Issue by lolaBerkowitz** [petersenpeter/phy2-plugins#3]
Phy2 environment installed on windows 10 x64 in using conda. 

I keep receiving this error: 

``` 
17:28:35.442 [D] actions:214          Traceback (most recent call last):
  File "c:\users\schafferlab\github\phy\phy\gui\actions.py", line 211, in wrapped
    return callback(*args)
  File "C:\Users\schafferlab\.phy\plugins\recluster.py", line 242, in MahalanobisDist
    spike_ids = controller.selector.select_spikes(cluster_ids)
AttributeError: 'SpikeSelector' object has no attribute 'select_spikes'
```

I've tried multiple install approaches for phy enviornment (development version  & standard install). I also recompiled klustakwik with VS2019, though I'll get this error without recompiling as well. Plugins are in ~/.phy/plugins, phy_config.py is updated, and tempdir.py has been saved to ~/phy/utils. 

Any suggestions?

**Comment by petersenpeter** [comment]
Hi Laura

@ThomasHainmueller did the phy2 version of the plugins so I have little help to provide. Perhaps phy2 has been updated since the plugins was written. Are you sure you installed phy2 plugins and not the phy1 version? 

@ThomasHainmueller Perhaps you have a solution?

**Comment by lolaBerkowitz** [comment]
Not sure about the versions. I cloned your repo a week or so ago, and installed those.

Maybe it's important to note that SplitshortISI works. I just get the error for recluster class plugins. 

I'll look again at the phy repo issues now that I know it's related to the controller structure. Thanks!

**Comment by ThomasHainmueller** [comment]
Hm...that's a tough one. If the function names have changed in a more recent version of phy I think the only way to fix it would be to go through the most recent example plug ins and find out how the spike-selection is called these days. That's how I upgraded the plugins from phy1 to phy2. Unfortunately, I don't really have a quick fix here =/

**Comment by lolaBerkowitz** [comment]
Great. I'll give that a try.
